import { useState } from "react";
import SideForm from "./components/SideForm";
import "./App.css";

function App() {
  const defaultTitle = "Default Title Generated by AI";

  const defaultDescription =
    "Default Description  Generated by AI. Default Description  Generated by AI.";

  const defaultButtonText = "AI generated Button";

  const defaultImageUrl =
    "https://images.unsplash.com/photo-1506152983158-b4a74a01c721?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=873&q=80";

  const [title, setTitle] = useState<string>(defaultTitle);
  const [description, setDescription] = useState<string>(defaultDescription);
  const [buttonText, setButtonText] = useState<string>(defaultButtonText);
  const [imageUrl, setImageUrl] = useState<string>(defaultImageUrl);

  // const formProbs = {
  //   title,
  //   description,
  //   buttonText,
  //   imageUrl,
  //   changeTitle: (value: string) => {
  //     setTitle(value);
  //   },
  //   changeDescription: (value: string) => {
  //     setDescription(value);
  //   },

  //   changeButtonText: (value: string) => {
  //     setButtonText(value);
  //   },

  //   changeImageUrl: (value: string) => {
  //     setImageUrl(value);
  //   },
  // };

  return (
    <div className="App">
      <SideForm
        title={title}
        description={description}
        buttonText={buttonText}
        onTitleChange={(value: string) => setTitle(value)}
        onDescriptionChange={(value: string) => setDescription(value)}
        onButtonTextChange={(value: string) => setButtonText(value)}
        onImageUrlChange={(value: string) => setImageUrl(value)}
      ></SideForm>
      <div className="hero">
        <div className="hero-details">
          <h2>LUXURY BRAND FOR YOU</h2>
          <h1>{title}</h1>

          <p>{description}</p>

          <button>{buttonText}</button>
        </div>
        <div className="image">
          <img alt="hero section image" src={imageUrl}></img>
        </div>
      </div>
    </div>
  );
}

export default App;
